name: final_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  flutter_facebook_auth: ^6.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  lottie: ^2.6.0
  shared_preferences: ^2.1.1
  easy_localization: ^3.0.3
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^8.0.0
  http: ^0.13.6
  model_viewer_plus: ^1.7.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/localization/en.json
    - lib/localization/ru.json
    - lib/localization/kk.json
    - assets/animations/loading.json
    - assets/images/
    - assets/3d_models/
    - assets/images/start.jpg
    - assets/images/lespaul.jpg
    - assets/images/gsmini.png
    - assets/images/cg162c.jpg
    - assets/images/custom.jpg
    - assets/images/standart.jpg
    - assets/images/concert.jpg
    - assets/images/genesis.jpg
    - assets/images/hummingbird.jpg
    - assets/images/classical2.png
    - assets/translations/
    - assets/animations/