
name: final_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  flutter_facebook_auth: ^5.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  lottie: ^2.6.0
  shared_preferences: ^2.1.1
  easy_localization: ^3.0.3
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  google_sign_in: ^6.1.6
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/localization/en.json
    - lib/localization/ru.json
    - lib/localization/kz.json
    - assets/animations/loading.json
  uses-material-design: true